using HRDocs.Infrastructure;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace HRDocs.Api.Services;
public sealed class PdfService
{
    public byte[] GenerateAcknowledgment(DocumentRequest r) => Document.Create(d => d.Page(p =>
    {
        p.Size(PageSizes.A4); p.Margin(40); p.DefaultTextStyle(x => x.FontSize(10));
        p.Header().Column(c => { c.Item().AlignCenter().Text("HR DOCUMENT RECEIVING ACKNOWLEDGMENT").Bold().FontSize(18).FontColor(Colors.Blue.Darken2); c.Item().AlignCenter().Text("Official receiving proof").FontColor(Colors.Grey.Darken1); });
        p.Content().PaddingVertical(25).Column(c =>
        {
            c.Spacing(10); c.Item().Border(1).BorderColor(Colors.Grey.Lighten2).Padding(15).Table(t => { t.ColumnsDefinition(x => { x.ConstantColumn(130); x.RelativeColumn(); }); Row(t, "Tracking number", r.TrackingNumber); Row(t, "Control number", r.ControlNumber ?? "—"); Row(t, "Status", r.Status.ToString()); Row(t, "Document title", r.Title); Row(t, "Document type", r.DocumentType.Name); Row(t, "Submitted by", r.SubmittedByUser.FullName); Row(t, "Sender department", r.SenderDepartment.Name); Row(t, "Recipient department", r.RecipientDepartment.Name); Row(t, "Received on", r.UpdatedAtUtc.ToString("dd MMM yyyy, HH:mm 'UTC'")); });
            c.Item().Text("Description").Bold(); c.Item().Text(string.IsNullOrWhiteSpace(r.Description) ? "No description provided." : r.Description);
            if (!string.IsNullOrWhiteSpace(r.AdminRemarks)) { c.Item().Text("HR remarks").Bold(); c.Item().Text(r.AdminRemarks); }
            c.Item().PaddingTop(20).Row(row => { foreach (var s in r.Signatures.OrderBy(x => x.SignedAtUtc)) row.RelativeItem().PaddingRight(15).Column(sc => { if (TryImage(s.SignatureDataUrl, out var bytes)) sc.Item().Height(55).Image(bytes).FitArea(); sc.Item().BorderTop(1).PaddingTop(4).Text($"{s.SignerUser.FullName} ({s.SignerRole})").Bold(); sc.Item().Text(s.SignedAtUtc.ToString("dd MMM yyyy HH:mm 'UTC'")).FontSize(8); }); });
        });
        p.Footer().AlignCenter().Text(x => { x.Span("Generated by HRDocs • "); x.CurrentPageNumber(); x.Span(" / "); x.TotalPages(); });
    })).GeneratePdf();
    private static void Row(TableDescriptor t, string label, string value) { t.Cell().PaddingVertical(4).Text(label).SemiBold(); t.Cell().PaddingVertical(4).Text(value); }
    private static bool TryImage(string data, out byte[] bytes) { bytes = []; try { var i = data.IndexOf(','); if (i < 0) return false; bytes = Convert.FromBase64String(data[(i + 1)..]); return true; } catch { return false; } }
}
